version: '3'
services:
#  bot:
#    image: "craigham/yahoo-bot:latest"
#    volumes:
#      - /home/craigh/bot/cache:/app/.cache

#  beat:
#    image: "craigham/yahoo-bot:latest"
#    command: [celery, beat, --app=worker.app, --loglevel=INFO]

  worker:
    image: worker
    command: [celery, app.worker, --app=worker.app, --concurrency=20, --loglevel=DEBUG]
    environment: &env
      - CELERY_BROKER_URL=amqp://guest:guest@192.168.1.20:5672/fantasy_bot