version: '3'
services:
#  bot:
#    image: "craigham/yahoo-bot:latest"
#    volumes:
#      - /home/craigh/bot/cache:/app/.cache

#  beat:
#    image: "craigham/yahoo-bot:latest"
#    command: [celery, beat, --app=worker.app, --loglevel=INFO]

  # worker:
  #   image: worker
  #   command: "celery worker -A csh_fantasy_bot.celery_app:app --loglevel=info"
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@192.168.1.20:5672/fantasy_bot

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  #     - XPACK_MONITORING_ENABLED=false
  redis:
    image: redis:6.0.10
    hostname: redis
    volumes:
     - /Users/craigh/dev/fantasy_bot/redis/data:/data
     - /Users/craigh/dev/fantasy_bot/redis/redis.conf:/usr/local/etc/redis/redis.conf
    
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
  # kibana:
  #   image: docker.elastic.co/kibana/kibana-oss:6.8.2
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    container_name: rabbitmq

  # flower:
  #   image: craigham/flower
  #   ports:
  #     - "8887:8887"
  #   environment:
  #     - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672
  #     - FLOWER_PORT=8887
  #     - CELERY_TIMEZONE='America/Pacific'

#   rebrow:
#     image: marian/rebrow
#     ports:
#       - "5001:5001"
# #    networks:
# #      - fantasy-bot
# #      - proxy
#     depends_on:
#       - redis

